print('Các ví dụ liên quan đến Lists ...')
print('--------------------------------------------')

sampleTuple = (1, 2, -5, 3, 11, 9, 30, 22, 15)
lists = list(sampleTuple)
print(' - sampleTuple : ' + str(sampleTuple))
print(' - lists: ' + str(lists) + ', len = ' + str(len(lists)))
print(' - max(lists): ' + str(max(lists)))
print(' - min(lists): ' + str(min(lists)))
lists.append(100)
print(' - lists.append(100): ' + str(lists))
print('--------------------------------------------')
lists.extend((77, 88, 99))
lists.extend((111, 222, 333))
print(' - lists.extend((77, 88, 99)): ')
print(' - lists.extend((111, 222, 333)): ')
print(' - ' + str(lists))
print('--------------------------------------------')
lists.insert(2, 10000)
print(' - lists.insert(2, 10000): ' + str(lists))
print('--------------------------------------------')
lists.reverse()
print(' - lists.reverse(): ' + str(lists))
print('--------------------------------------------')
lists.remove(10000)
print(' - lists.remove(10000): ' + str(lists))
print('--------------------------------------------')
pickItem = lists.pop(0)
print(' - lists.pop(): ' + str(pickItem) + ", lists = " + str(lists))
print('--------------------------------------------')
lists.sort()
print(' - lists.sort(): ' + str(lists))
print('--------------------------------------------')
lists.clear()
print(' - lists.clear(): ' + str(lists))